# Sorgente dell'elenco mansioni (WP-006). Genera data/occupations.csv con: python3 scripts/data-src/occupations.py
# Colonne: slug, label_it, category, isco_code (ISCO-08, 4 cifre), synonyms (separati da |), note
# Etichette inclusive (maschile/femminile). I codici ISCO segnati "verificare" vanno controllati su ESCO prima del lancio.
import csv, os

V = "verificare codice ISCO"
R = []  # (slug, label, category, isco, [synonyms], note)
def add(cat, slug, label, isco, syn, note=""):
    R.append((slug, label, cat, isco, syn, note))

c = "ristorazione"
add(c, "cameriere", "Cameriere/a di sala", "5131", ["cameriere", "cameriera", "addetto sala", "addetta sala", "commis di sala", "runner", "chef de rang", "cameriere ai tavoli"])
add(c, "maitre", "Maître di sala", "5131", ["maitre", "responsabile di sala", "capo sala", "direttore di sala"])
add(c, "sommelier", "Sommelier", "5131", ["esperto vini", "cantiniere di sala"])
add(c, "barista", "Barista", "5132", ["barman", "barlady", "bartender", "banconista bar", "addetto caffetteria", "caffettiere"])
add(c, "cuoco", "Cuoco/a", "5120", ["cuoco", "cuoca", "capo partita", "chef de partie", "cuoco di linea", "cuoco mensa", "sushiman"])
add(c, "chef", "Chef / capo cuoco", "3434", ["capo cuoco", "executive chef", "sous chef", "responsabile di cucina"])
add(c, "aiuto-cuoco", "Aiuto cuoco/a", "9412", ["aiuto cuoco", "aiuto cuoca", "commis di cucina", "aiuto cucina", "addetto preparazioni"])
add(c, "lavapiatti", "Lavapiatti", "9412", ["lavastoviglie", "addetto lavaggio stoviglie", "plongeur", "stewarding"])
add(c, "pizzaiolo", "Pizzaiolo/a", "5120", ["pizzaiolo", "pizzaiola", "aiuto pizzaiolo", "forno a legna"])
add(c, "rosticcere", "Rosticcere / addetto rosticceria", "5120", ["rosticcere", "addetto rosticceria", "friggitore", "girarrosto"])
add(c, "pasticcere", "Pasticcere/a", "7512", ["pasticcere", "pasticciera", "aiuto pasticcere", "pastry chef"])
add(c, "panettiere", "Panettiere/a / fornaio", "7512", ["panettiere", "panettiera", "fornaio", "fornaia", "panificatore", "addetto forno"])
add(c, "gelatiere", "Gelatiere/a", "7512", ["gelatiere", "gelatiera", "addetto gelateria"])
add(c, "addetto-fast-food", "Addetto/a fast food e ristorazione veloce", "5246", ["addetto fast food", "crew member", "addetto ristorazione veloce", "addetto self service"])
add(c, "addetto-mensa", "Addetto/a mensa e ristorazione collettiva", "5246", ["addetto mensa", "addetta mensa", "scodellatore", "scodellatrice", "porzionatore", "ristorazione collettiva"])
add(c, "addetto-catering", "Addetto/a catering e banqueting", "5131", ["catering", "banqueting", "cameriere extra", "extra per eventi", "addetto buffet"])
add(c, "responsabile-ristorante", "Responsabile di ristorante o bar", "1412", ["direttore ristorante", "restaurant manager", "responsabile punto ristoro", "gestore bar"])

c = "turismo"
add(c, "receptionist-hotel", "Receptionist d'albergo", "4224", ["receptionist hotel", "addetto ricevimento", "front office hotel", "portiere d'albergo", "portiere notturno", "night auditor", "concierge"])
add(c, "cameriera-ai-piani", "Cameriere/a ai piani", "9112", ["cameriera ai piani", "cameriere ai piani", "addetta camere", "room attendant", "housekeeping"])
add(c, "governante", "Governante d'albergo", "5151", ["housekeeper", "responsabile piani", "capo cameriera"])
add(c, "facchino-hotel", "Facchino/a d'albergo", "9621", ["facchino d'albergo", "portabagagli", "bell boy", "valet"])
add(c, "animatore-turistico", "Animatore/animatrice turistico", "3423", ["animatore", "animatrice", "animazione villaggi", "mini club", "capo animazione"], V)
add(c, "guida-turistica", "Guida turistica / accompagnatore", "5113", ["guida turistica", "accompagnatore turistico", "tour leader", "guida museale"])
add(c, "agente-viaggi", "Consulente di agenzia viaggi", "4221", ["agente di viaggio", "addetto agenzia viaggi", "travel agent", "consulente viaggi", "booking"])
add(c, "bagnino", "Bagnino/a / assistente bagnanti", "5419", ["bagnino", "bagnina", "assistente bagnanti", "lifeguard"])
add(c, "maestro-sci", "Maestro/a di sci e snowboard", "3422", ["maestro di sci", "maestra di sci", "istruttore sci", "maestro snowboard"])
add(c, "addetto-impianti-risalita", "Addetto/a impianti di risalita", "8343", ["addetto seggiovia", "skilift", "addetto funivia", "impianti a fune"], V)
add(c, "addetto-noleggio", "Addetto/a noleggio (sci, bici, auto)", "5249", ["noleggio sci", "noleggio bici", "rent a car", "addetto noleggio auto"], V)
add(c, "addetto-stabilimento-balneare", "Addetto/a stabilimento balneare", "9629", ["spiaggino", "addetto spiaggia", "lido", "stabilimento balneare"])
add(c, "hostess-eventi", "Hostess e steward per eventi e fiere", "4229", ["hostess", "steward eventi", "hostess fiere", "accoglienza eventi", "congressi"], V)

c = "commercio"
add(c, "commesso", "Commesso/a / addetto vendite", "5223", ["commesso", "commessa", "addetto vendite", "addetta vendite", "sales assistant", "venditore negozio", "shop assistant", "commesso abbigliamento"])
add(c, "cassiere", "Cassiere/a", "5230", ["cassiere", "cassiera", "addetto cassa", "addetta cassa", "cassa supermercato"])
add(c, "scaffalista", "Scaffalista / addetto rifornimento", "9334", ["addetto rifornimento scaffali", "riordino merce", "merchandiser gdo", "addetto reparto"])
add(c, "banconista-gastronomia", "Banconista gastronomia e salumeria", "5223", ["banconista", "addetto banco gastronomia", "salumiere", "salumiera", "banco salumi e formaggi"])
add(c, "macellaio", "Macellaio/a", "7511", ["macellaio", "macellaia", "addetto macelleria", "disossatore", "norcino", "banco carne"])
add(c, "pescivendolo", "Pescivendolo/a / addetto pescheria", "7511", ["pescivendolo", "pescivendola", "addetto pescheria", "banco pesce"])
add(c, "addetto-ortofrutta", "Addetto/a ortofrutta", "5223", ["addetto ortofrutta", "fruttivendolo", "fruttivendola", "reparto frutta e verdura"])
add(c, "responsabile-negozio", "Responsabile di negozio / store manager", "1420", ["store manager", "responsabile punto vendita", "direttore negozio", "capo reparto", "vice direttore supermercato"])
add(c, "venditore-ambulante", "Venditore/venditrice ambulante e di mercato", "5211", ["ambulante", "venditore mercato", "banco mercato", "mercatino"])
add(c, "agente-commercio", "Agente di commercio / rappresentante", "3322", ["agente di commercio", "rappresentante", "venditore", "commerciale", "sales representative", "area manager vendite"])
add(c, "venditore-porta-a-porta", "Venditore/venditrice porta a porta", "5243", ["porta a porta", "venditore a domicilio", "door to door"])
add(c, "operatore-call-center", "Operatore/operatrice call center (vendita)", "5244", ["call center", "telemarketing", "teleselling", "operatore telefonico outbound", "televenditore"])
add(c, "customer-care", "Addetto/a assistenza clienti", "4222", ["customer care", "customer service", "assistenza clienti", "servizio clienti", "helpdesk clienti", "inbound"])
add(c, "visual-merchandiser", "Visual merchandiser / vetrinista", "3432", ["visual merchandiser", "vetrinista", "allestitore vetrine"])
add(c, "commesso-farmacia", "Commesso/a di farmacia e parafarmacia", "3213", ["commessa farmacia", "banconista parafarmacia", "addetto parafarmacia"])
add(c, "ottico", "Ottico/a", "3254", ["ottico", "ottica", "optometrista", "tecnico ottico"])
add(c, "fiorista", "Fiorista", "5223", ["addetto negozio fiori", "composizioni floreali"], V)
add(c, "promoter", "Promoter / hostess promozionale", "5242", ["hostess promozionale", "degustazioni", "dimostratore", "promoter supermercato"])
add(c, "volantinaggio", "Addetto/a volantinaggio", "9621", ["distributore volantini", "distribuzione pubblicità"], V)
add(c, "addetto-ecommerce", "Addetto/a e-commerce", "4110", ["ecommerce", "e-commerce", "gestione ordini online", "marketplace", "amazon seller"], V)
add(c, "venditore-auto", "Venditore/venditrice di auto", "5223", ["venditore auto", "consulente vendita auto", "salone auto", "concessionaria"], V)

c = "logistica"
add(c, "magazziniere", "Magazziniere/a", "4321", ["magazziniere", "magazziniera", "addetto magazzino", "addetta magazzino", "operatore di magazzino", "warehouse operator"])
add(c, "mulettista", "Mulettista / carrellista", "8344", ["carrellista", "carrello elevatore", "patentino muletto", "conduttore muletto", "reach truck"])
add(c, "picker", "Addetto/a picking e preparazione ordini", "9333", ["picking", "preparazione ordini", "order picker", "allestitore ordini"])
add(c, "facchino", "Facchino/a / addetto carico e scarico", "9333", ["facchino", "facchina", "carico e scarico", "scaricatore", "movimentazione merci", "traslocatore", "traslochi"])
add(c, "imballatore", "Addetto/a imballaggio e confezionamento", "9321", ["imballatore", "imballatrice", "confezionatore", "confezionatrice", "packaging manuale", "addetto confezionamento", "incartatore"])
add(c, "responsabile-magazzino", "Responsabile di magazzino e logistica", "1324", ["responsabile magazzino", "capo magazzino", "warehouse manager", "responsabile logistica", "capoturno magazzino"])
add(c, "impiegato-logistica", "Impiegato/a logistica e spedizioni", "4323", ["impiegato logistica", "addetto spedizioni", "spedizioniere", "traffic", "pianificatore trasporti"])
add(c, "addetto-smistamento", "Addetto/a smistamento pacchi", "9333", ["smistamento pacchi", "sorter", "addetto hub", "smistatore"], V)
add(c, "inventarista", "Inventarista", "4321", ["addetto inventari", "conteggio inventario"])
add(c, "postino", "Portalettere / postino", "4412", ["postino", "postina", "portalettere", "recapito posta"])
add(c, "gruista", "Gruista", "8343", ["operatore gru", "gru a torre", "autogru"])

c = "trasporti"
add(c, "autista-b", "Autista patente B / furgone", "8322", ["autista patente b", "autista furgone", "driver", "autista consegne", "corriere", "autista corriere espresso"])
add(c, "rider", "Rider / fattorino consegne", "9621", ["fattorino", "fattorina", "consegne a domicilio", "pony express", "delivery"])
add(c, "autista-camion", "Autista camion patente C/CE", "8332", ["autista patente c", "autista patente ce", "camionista", "autotrasportatore", "bilico", "autista mezzi pesanti", "autista cqc"])
add(c, "autista-adr", "Autista trasporto merci pericolose (ADR)", "8332", ["autista adr", "cisternista", "trasporto carburanti", "autista cisterna"])
add(c, "autista-autobus", "Autista di autobus e pullman", "8331", ["autista autobus", "autista pullman", "autista patente d", "autista scuolabus", "conducente bus", "autista bus turistici"])
add(c, "autista-ncc", "Autista NCC / taxi", "8322", ["autista ncc", "noleggio con conducente", "tassista", "taxi", "chauffeur", "autista privato"])
add(c, "marinaio", "Marinaio/a / personale di bordo", "8350", ["marinaio", "mozzo", "personale di coperta", "ormeggiatore", "equipaggio traghetti"])

c = "edilizia"
add(c, "muratore", "Muratore", "7112", ["muratrice", "operaio edile", "muratore specializzato", "capo squadra muratori"])
add(c, "manovale", "Manovale edile", "9313", ["manovale edile", "aiuto muratore", "operaio comune edile"])
add(c, "carpentiere", "Carpentiere edile", "7115", ["carpentiere edile", "casseforme", "carpentiere legno"])
add(c, "ferraiolo", "Ferraiolo", "7114", ["piegaferro", "armature cemento"])
add(c, "piastrellista", "Piastrellista", "7122", ["posatore piastrelle", "posatore rivestimenti", "mosaicista"])
add(c, "parquettista", "Posatore/posatrice di pavimenti e parquet", "7122", ["parquettista", "posatore pavimenti", "posatore parquet", "pavimentista"])
add(c, "imbianchino", "Imbianchino / pittore edile", "7131", ["imbianchino", "pittore edile", "tinteggiatore", "decoratore edile"])
add(c, "cartongessista", "Cartongessista", "7123", ["montatore cartongesso", "controsoffitti"])
add(c, "intonacatore", "Intonacatore / stuccatore", "7123", ["intonacatore", "stuccatore", "rasatore", "intonaci"])
add(c, "copritetto", "Copritetto / impermeabilizzatore", "7121", ["copritetto", "tettoista", "impermeabilizzatore", "guaine", "coperture"])
add(c, "lattoniere", "Lattoniere", "7213", ["lattoneria", "grondaie"])
add(c, "serramentista", "Serramentista / montatore di infissi", "7125", ["serramentista", "montatore infissi", "posatore serramenti", "installatore finestre", "vetraio"], V)
add(c, "geometra", "Geometra / tecnico di cantiere", "3112", ["geometra", "tecnico di cantiere", "assistente di cantiere", "contabilità di cantiere", "topografo"])
add(c, "capocantiere", "Capocantiere", "3123", ["capo cantiere", "direttore tecnico di cantiere", "site manager", "caposquadra edile"])
add(c, "addetto-demolizioni", "Addetto/a demolizioni e bonifiche", "7119", ["demolizioni", "bonifica amianto", "scoibentazione"], V)
add(c, "ponteggiatore", "Ponteggiatore", "7119", ["montatore ponteggi", "ponteggi"])
add(c, "operaio-stradale", "Operaio/a stradale", "9312", ["operaio stradale", "asfaltista", "stradino", "segnaletica stradale", "cantoniere"])
add(c, "escavatorista", "Escavatorista / operatore macchine movimento terra", "8342", ["escavatorista", "ruspista", "palista", "operatore movimento terra", "macchine operatrici"])

c = "impianti"
add(c, "idraulico", "Idraulico/a", "7126", ["idraulico", "idraulica", "termoidraulico", "installatore idraulico", "impianti idraulici"])
add(c, "elettricista", "Elettricista civile", "7411", ["elettricista", "installatore elettrico", "impianti elettrici", "aiuto elettricista"])
add(c, "elettricista-industriale", "Elettricista industriale / manutentore elettrico", "7412", ["manutentore elettrico", "quadrista", "cablatore quadri elettrici", "elettromeccanico"])
add(c, "frigorista", "Frigorista / tecnico condizionamento", "7127", ["frigorista", "tecnico climatizzazione", "condizionatori", "tecnico refrigerazione", "installatore clima"])
add(c, "tecnico-caldaie", "Tecnico/a caldaie e impianti termici", "7126", ["caldaista", "manutentore caldaie", "tecnico caldaie", "impianti termici", "conduttore caldaie"])
add(c, "installatore-fotovoltaico", "Installatore/installatrice fotovoltaico", "7411", ["installatore fotovoltaico", "pannelli solari", "impianti fotovoltaici", "installatore energie rinnovabili"])
add(c, "antennista", "Antennista / installatore reti e fibra", "7422", ["antennista", "installatore fibra", "tecnico fibra ottica", "installatore reti", "cablaggio strutturato"])
add(c, "manutentore-edifici", "Manutentore/manutentrice di edifici (tuttofare)", "7119", ["manutentore", "tuttofare", "handyman", "manutenzione stabili", "manutentore generico"], V)
add(c, "ascensorista", "Tecnico/a ascensorista", "7412", ["ascensorista", "tecnico ascensori", "manutentore ascensori"])
add(c, "installatore-allarmi", "Installatore/installatrice di sistemi di allarme", "7421", ["installatore allarmi", "videosorveglianza", "antintrusione", "tecnico impianti di sicurezza"])

c = "industria"
add(c, "operaio-produzione", "Operaio/a di produzione", "9329", ["operaio", "operaia", "addetto produzione", "addetta produzione", "operaio generico", "operaio di linea", "addetto alla linea"])
add(c, "operatore-macchine", "Operatore/operatrice macchine automatiche", "8189", ["operatore macchine", "conduttore macchine", "macchinista industriale", "addetto macchine automatiche"])
add(c, "addetto-confezionatrici", "Addetto/a macchine confezionatrici", "8183", ["confezionatrici", "imbottigliamento", "etichettatrici", "linea di confezionamento", "blisteratrici"])
add(c, "operatore-alimentare", "Operatore/operatrice industria alimentare", "8160", ["industria alimentare", "addetto produzione alimentare", "operaio alimentare", "salumificio", "caseificio", "conserviero"])
add(c, "addetto-macello", "Addetto/a macello e sezionamento carni", "7511", ["macello", "sezionamento carni", "mattatoio", "disosso"])
add(c, "operatore-cnc", "Operatore/operatrice CNC", "7223", ["operatore cnc", "macchine utensili", "centri di lavoro", "programmatore cnc"])
add(c, "tornitore", "Tornitore/tornitrice", "7223", ["tornitore", "tornio", "tornitore cnc"])
add(c, "fresatore", "Fresatore/fresatrice", "7223", ["fresatore", "fresa", "fresatore cnc"])
add(c, "saldatore", "Saldatore/saldatrice", "7212", ["saldatore", "saldatrice", "saldatura tig", "saldatura mig", "saldatura a filo", "saldocarpentiere"])
add(c, "carpentiere-metallico", "Carpentiere metallico", "7214", ["carpenteria metallica", "montatore strutture metalliche", "lamierista"])
add(c, "fabbro", "Fabbro", "7221", ["fabbro ferraio", "cancelli", "inferriate"])
add(c, "attrezzista", "Attrezzista / stampista", "7222", ["stampista", "attrezzista stampi", "costruttore stampi", "attrezzista cnc"])
add(c, "montatore-meccanico", "Montatore/montatrice meccanico", "8211", ["montatore meccanico", "assemblatore meccanico", "assemblaggio macchine", "montaggio meccanico", "montatore"])
add(c, "assemblatore-elettronico", "Assemblatore/assemblatrice elettronico", "8212", ["assemblatore elettronico", "cablatore", "montaggio componenti elettronici", "saldatura a stagno"])
add(c, "manutentore-meccanico", "Manutentore meccanico industriale", "7233", ["manutentore meccanico", "manutenzione impianti industriali", "meccanico industriale", "manutentore macchine", "meccanico macchine agricole"])
add(c, "verniciatore", "Verniciatore/verniciatrice", "7132", ["verniciatore", "verniciatura", "verniciatore a spruzzo", "verniciatore carrozzeria"])
add(c, "stampaggio-plastica", "Operatore/operatrice stampaggio plastica", "8142", ["stampaggio plastica", "presse ad iniezione", "addetto presse", "stampaggio"])
add(c, "operatore-chimico", "Conduttore/conduttrice di impianti chimici", "8131", ["impianti chimici", "operatore chimico", "produzione farmaceutica", "addetto reparto chimico"])
add(c, "operatore-fonderia", "Operatore/operatrice di fonderia", "8121", ["fonderia", "fonditore", "colata", "pressofusione"])
add(c, "controllo-qualita", "Addetto/a controllo qualità", "7543", ["controllo qualità", "collaudatore", "collaudatrice", "quality control", "ispettore qualità"])
add(c, "lavanderia-industriale", "Addetto/a lavanderia industriale", "8157", ["lavanderia industriale", "operatore lavanderia industriale", "stireria industriale"])
add(c, "operatore-tessile", "Operatore/operatrice tessile", "8152", ["tessile", "tessitore", "tessitrice", "filatura", "telaio", "operaio tessile"])
add(c, "cucitrice", "Cucitore/cucitrice industriale", "8153", ["cucitrice", "cucitore", "macchina da cucire", "confezione abbigliamento", "orlatrice"])
add(c, "responsabile-produzione", "Responsabile di produzione", "1321", ["responsabile produzione", "capo reparto produzione", "direttore di stabilimento", "plant manager", "capoturno produzione"])

c = "artigianato"
add(c, "falegname", "Falegname", "7522", ["ebanista", "mobiliere", "falegnameria"])
add(c, "operatore-macchine-legno", "Operatore/operatrice macchine per il legno", "7523", ["macchine legno", "sezionatrice", "pantografo", "bordatrice", "squadratrice"])
add(c, "tappezziere", "Tappezziere/a", "7534", ["tappezziere", "tappezziera", "imbottitore", "divani"])
add(c, "calzolaio", "Calzolaio/a", "7536", ["calzolaio", "calzolaia", "riparazione scarpe", "calzaturiero"])
add(c, "pellettiere", "Pellettiere / lavorazione pelle", "7536", ["pellettiere", "pelletteria", "borse", "lavorazione pelle"], V)
add(c, "sarto", "Sarto/sarta / modellista", "7531", ["sarto", "sarta", "modellista", "riparazioni sartoriali", "rammendatrice"])
add(c, "orafo", "Orafo/orafa", "7313", ["orafo", "orafa", "gioielliere", "incastonatore", "incastonatrice"])
add(c, "orologiaio", "Orologiaio/a", "7311", ["orologiaio", "riparazione orologi"])
add(c, "restauratore", "Restauratore/restauratrice", "3433", ["restauratore", "restauratrice", "restauro mobili", "restauro"], V)
add(c, "marmista", "Marmista / scalpellino", "7113", ["scalpellino", "lavorazione pietra", "lapidi"])
add(c, "ceramista", "Ceramista", "7314", ["vasaio", "decoratore ceramica"])
add(c, "tipografo", "Tipografo/a / operatore di stampa", "7322", ["tipografo", "tipografa", "macchinista stampa", "stampa offset", "stampa digitale", "serigrafo"])
add(c, "legatore", "Legatore/legatrice", "7323", ["legatore", "legatoria", "cartotecnica"])

c = "auto"
add(c, "meccanico-auto", "Meccanico/a auto", "7231", ["meccanico", "meccanico auto", "autoriparatore", "meccatronico", "motorista", "tagliandi"])
add(c, "meccanico-mezzi-pesanti", "Meccanico/a mezzi pesanti", "7231", ["meccanico camion", "meccanico mezzi pesanti", "meccanico veicoli industriali"])
add(c, "meccanico-moto", "Meccanico/a moto e scooter", "7231", ["meccanico moto", "motociclette", "officina scooter"])
add(c, "meccanico-bici", "Meccanico/a di biciclette", "7234", ["meccanico bici", "riparazione biciclette", "e-bike"])
add(c, "elettrauto", "Elettrauto", "7412", ["elettricista auto", "diagnosi elettronica auto"])
add(c, "carrozziere", "Carrozziere/a", "7213", ["carrozziere", "carrozzeria", "battilastra", "lattoniere auto", "riparatore carrozzeria"])
add(c, "gommista", "Gommista", "7231", ["cambio gomme", "pneumatici", "equilibratura"])
add(c, "addetto-autolavaggio", "Addetto/a autolavaggio", "9122", ["autolavaggio", "lavaggio auto", "car wash", "detailing"])
add(c, "accettatore-officina", "Accettatore/accettatrice officina", "4229", ["accettatore", "service advisor", "accettazione officina"], V)

c = "agricoltura"
add(c, "bracciante", "Bracciante / operaio agricolo", "9211", ["bracciante", "operaio agricolo", "operaia agricola", "raccolta frutta", "vendemmia", "vendemmiatore", "raccolta olive", "stagionale agricolo", "raccoglitore"])
add(c, "trattorista", "Trattorista / conduttore macchine agricole", "8341", ["conduttore trattore", "macchine agricole", "mietitrebbia", "operatore agromeccanico"])
add(c, "addetto-stalla", "Addetto/a stalla / mungitore", "9212", ["addetto stalla", "mungitore", "mungitrice", "allevamento", "stalliere"])
add(c, "allevatore", "Allevatore/allevatrice", "6121", ["allevatore", "allevatrice", "zootecnico", "allevamento bestiame"])
add(c, "giardiniere", "Giardiniere/a / manutentore del verde", "6113", ["giardiniere", "giardiniera", "manutenzione del verde", "potatore", "tagliaerba", "vivaista", "florovivaista"])
add(c, "addetto-vivaio", "Addetto/a vivaio e serre", "9214", ["vivaio", "serre", "serricoltura", "addetto serra", "orticoltura"])
add(c, "operaio-forestale", "Operaio/a forestale / boscaiolo", "6210", ["operaio forestale", "boscaiolo", "motoseghista", "taglialegna"])
add(c, "viticoltore", "Viticoltore/viticoltrice / cantiniere", "6112", ["viticoltore", "vignaiolo", "cantiniere", "cantina", "potatore vigneto"])
add(c, "addetto-frantoio", "Addetto/a frantoio e oleificio", "8160", ["frantoio", "frantoiano", "oleificio", "molitura olive"], V)
add(c, "agronomo", "Agronomo/agronoma / perito agrario", "2132", ["agronomo", "agronoma", "perito agrario", "agrotecnico", "consulente agricolo"])
add(c, "enologo", "Enologo/a", "2132", ["enologo", "enologa", "enotecnico"], V)
add(c, "pescatore", "Pescatore/pescatrice / acquacoltura", "6222", ["pescatore", "pescatrice", "acquacoltura", "allevamento ittico"])
add(c, "apicoltore", "Apicoltore/apicoltrice", "6123", ["apicoltore", "apicoltrice", "miele"])
add(c, "toelettatore", "Toelettatore/toelettatrice / cura animali", "5164", ["toelettatore", "toelettatura", "toilettatura", "pet groomer", "dog sitter", "addetto pensione animali"])
add(c, "veterinario", "Veterinario/a", "2250", ["veterinario", "veterinaria", "medico veterinario"])
add(c, "assistente-veterinario", "Assistente veterinario / tecnico veterinario", "3240", ["assistente veterinario", "tecnico veterinario", "infermiere veterinario"])

c = "sanita"
add(c, "infermiere", "Infermiere/a", "2221", ["infermiere", "infermiera", "infermiere professionale", "infermiere di reparto", "infermiere domiciliare"])
add(c, "oss", "Operatore/operatrice socio-sanitario (OSS)", "5321", ["operatore socio sanitario", "operatrice socio sanitaria", "oss rsa", "oss ospedale"])
add(c, "asa", "Ausiliario/a socio-assistenziale (ASA)", "5321", ["ausiliario socio assistenziale", "ausiliaria socio assistenziale", "osa", "ausiliario rsa"])
add(c, "medico", "Medico di medicina generale", "2211", ["medico", "medico di base", "medico generico", "guardia medica", "medico di continuità assistenziale"])
add(c, "medico-specialista", "Medico specialista", "2212", ["specialista ambulatoriale", "chirurgo", "anestesista", "pediatra", "cardiologo"])
add(c, "fisioterapista", "Fisioterapista", "2264", ["fisioterapia", "riabilitazione", "terapista della riabilitazione"])
add(c, "farmacista", "Farmacista", "2262", ["farmacista collaboratore", "direttore di farmacia"])
add(c, "tecnico-radiologia", "Tecnico/a di radiologia", "3211", ["tecnico radiologia", "tsrm", "tecnico radiologo"])
add(c, "tecnico-laboratorio-biomedico", "Tecnico/a di laboratorio biomedico", "3212", ["tecnico laboratorio analisi", "tecnico di laboratorio biomedico", "tlb"])
add(c, "ostetrica", "Ostetrica/ostetrico", "2222", ["ostetrico"])
add(c, "logopedista", "Logopedista", "2266", ["logopedia"])
add(c, "psicologo", "Psicologo/a", "2634", ["psicologo", "psicologa", "psicoterapeuta"])
add(c, "odontotecnico", "Odontotecnico/a", "3214", ["odontotecnico", "protesi dentarie", "laboratorio odontotecnico"])
add(c, "aso", "Assistente di studio odontoiatrico (ASO)", "3251", ["assistente alla poltrona", "assistente dentista", "assistente studio dentistico"])
add(c, "igienista-dentale", "Igienista dentale", "3251", ["igienista dentale", "igiene dentale"])
add(c, "dentista", "Odontoiatra / dentista", "2261", ["dentista", "odontoiatra"])
add(c, "soccorritore", "Soccorritore / autista di ambulanza", "3258", ["soccorritore", "autista ambulanza", "autista soccorritore", "trasporto sanitario", "118"])
add(c, "accettazione-sanitaria", "Addetto/a accettazione e CUP", "4226", ["accettazione sanitaria", "cup", "front office clinica", "segreteria medica"])

c = "assistenza"
add(c, "badante", "Badante / assistente familiare", "5322", ["assistente familiare", "assistente anziani", "assistenza domiciliare", "caregiver", "badante convivente"])
add(c, "colf", "Colf / collaboratore/collaboratrice domestico", "9111", ["collaboratrice domestica", "collaboratore domestico", "domestica", "pulizie domestiche"])
add(c, "baby-sitter", "Baby sitter / tata", "5311", ["baby sitter", "babysitter", "tata", "nanny", "au pair"])
add(c, "educatore-nido", "Educatore/educatrice asilo nido", "2342", ["educatrice nido", "educatore nido", "asilo nido", "educatrice prima infanzia"])
add(c, "educatore-professionale", "Educatore/educatrice professionale", "3412", ["educatore professionale", "educatrice professionale", "educatore comunità", "educatore sociale", "educatore disabili"])
add(c, "assistente-sociale", "Assistente sociale", "2635", ["servizi sociali"])
add(c, "assistente-educativo", "Assistente educativo e alla comunicazione (AEC)", "5312", ["aec", "assistente educativo", "assistente alla persona scuola", "assistente alla comunicazione", "assistente all'autonomia"])
add(c, "mediatore-culturale", "Mediatore/mediatrice culturale", "3412", ["mediatore culturale", "mediatrice culturale", "mediatore linguistico"], V)
add(c, "animatore-sociale", "Animatore/animatrice sociale (RSA, centri diurni)", "3412", ["animatore rsa", "animatore sociale", "animatrice anziani", "centro diurno"], V)

c = "benessere"
add(c, "parrucchiere", "Parrucchiere/a / acconciatore", "5141", ["parrucchiere", "parrucchiera", "acconciatore", "acconciatrice", "hair stylist", "shampista"])
add(c, "barbiere", "Barbiere", "5141", ["barber"])
add(c, "estetista", "Estetista", "5142", ["centro estetico", "trattamenti viso e corpo", "epilazione", "make up artist", "truccatore", "truccatrice"])
add(c, "onicotecnica", "Onicotecnico/a / nail artist", "5142", ["onicotecnica", "onicotecnico", "nail artist", "ricostruzione unghie", "manicure", "pedicure"])
add(c, "massaggiatore", "Massaggiatore/massaggiatrice / operatore benessere", "3255", ["massaggiatore", "massaggiatrice", "massofisioterapista", "operatore spa", "centro benessere"])
add(c, "personal-trainer", "Istruttore/istruttrice fitness / personal trainer", "3423", ["personal trainer", "istruttore palestra", "istruttrice fitness", "istruttore sala pesi", "pilates", "yoga"])
add(c, "istruttore-nuoto", "Istruttore/istruttrice di nuoto", "3423", ["istruttore nuoto", "istruttrice nuoto", "acquagym"])
add(c, "allenatore", "Allenatore/allenatrice sportivo", "3422", ["allenatore", "allenatrice", "coach sportivo", "preparatore atletico", "istruttore calcio"])

c = "pulizie"
add(c, "addetto-pulizie", "Addetto/a alle pulizie", "9112", ["addetto pulizie", "addetta pulizie", "operatore pulizie", "pulizie uffici", "pulizie condomini", "pulizie ospedaliere", "impresa di pulizie"])
add(c, "addetto-sanificazione", "Addetto/a pulizie industriali e sanificazione", "9129", ["sanificazione", "pulizie industriali", "disinfestazione", "derattizzazione", "pulizie post cantiere"])
add(c, "lavavetri", "Lavavetri", "9123", ["pulizia vetri", "vetrate"])
add(c, "addetto-lavanderia", "Addetto/a lavanderia e stireria", "9121", ["lavanderia", "stireria", "stiratrice", "stiratore", "tintoria"])
add(c, "custode", "Custode / portiere di condominio", "5153", ["portiere", "portinaio", "portinaia", "portierato", "custode condominio"])
add(c, "operatore-ecologico", "Operatore/operatrice ecologico", "9611", ["operatore ecologico", "netturbino", "spazzino", "raccolta rifiuti", "autista compattatore"])
add(c, "selezione-rifiuti", "Addetto/a selezione rifiuti e riciclo", "9612", ["selezione rifiuti", "impianto riciclaggio", "cernita", "isola ecologica"])
add(c, "parcheggiatore", "Parcheggiatore / addetto parcheggio", "9629", ["addetto parcheggio", "valet parking", "garagista"])
add(c, "maggiordomo", "Maggiordomo / governante privato", "5152", ["governante privata", "butler"])
add(c, "operatore-funebre", "Operatore/operatrice funebre", "5163", ["necroforo", "operatore funebre", "addetto onoranze funebri", "cerimoniere funebre"])

c = "sicurezza"
add(c, "guardia-giurata", "Guardia giurata", "5414", ["gpg", "vigilante", "vigilanza armata", "guardia particolare giurata"])
add(c, "addetto-sicurezza", "Addetto/a alla sicurezza non armata", "5414", ["addetto sicurezza", "steward", "buttafuori", "addetto servizi di controllo", "security", "sorveglianza non armata"])
add(c, "addetto-antincendio", "Addetto/a antincendio", "5411", ["addetto antincendio", "vigile del fuoco aziendale", "squadra antincendio"])

c = "ufficio"
add(c, "impiegato-amministrativo", "Impiegato/a amministrativo", "4110", ["impiegato amministrativo", "impiegata amministrativa", "amministrazione", "back office", "impiegato d'ordine", "addetto ufficio"])
add(c, "segretario", "Segretario/a", "4120", ["segretaria", "segretario", "segreteria", "assistente amministrativa"])
add(c, "receptionist", "Receptionist / centralinista", "4226", ["centralinista", "front office", "accoglienza clienti", "portineria aziendale"])
add(c, "contabile", "Contabile / addetto contabilità", "4311", ["addetto contabilità", "addetta contabilità", "ragioniere", "ragioniera", "prima nota", "contabilità generale"])
add(c, "addetto-paghe", "Addetto/a paghe e contributi", "4313", ["addetto paghe", "payroll", "elaborazione cedolini", "buste paga"])
add(c, "commercialista", "Commercialista / esperto contabile", "2411", ["dottore commercialista", "revisore contabile", "esperto contabile"])
add(c, "operatore-caf", "Operatore/operatrice CAF e patronato", "3313", ["caf", "patronato", "730", "dichiarazione dei redditi", "operatore fiscale"], V)
add(c, "assistente-direzione", "Assistente di direzione", "3343", ["assistente di direzione", "executive assistant", "segretaria di direzione", "personal assistant"])
add(c, "office-manager", "Office manager / responsabile amministrativo", "3341", ["office manager", "responsabile ufficio", "capo ufficio", "responsabile amministrativo"])
add(c, "data-entry", "Addetto/a data entry", "4132", ["data entry", "inserimento dati", "digitazione dati"])
add(c, "archivista", "Archivista / addetto archivio", "4415", ["addetto archivio", "archiviazione documenti", "protocollo"])
add(c, "addetto-acquisti", "Addetto/a acquisti / buyer", "3323", ["buyer", "addetto acquisti", "ufficio acquisti", "approvvigionamenti", "purchasing"])
add(c, "ufficio-commerciale", "Addetto/a ufficio commerciale", "4110", ["ufficio commerciale", "sales support", "back office commerciale", "gestione ordini clienti", "inside sales"], V)
add(c, "addetto-risorse-umane", "Addetto/a risorse umane", "4416", ["addetto risorse umane", "ufficio personale", "hr", "amministrazione del personale"])
add(c, "recruiter", "Selezionatore/selezionatrice del personale", "2423", ["recruiter", "selezionatore", "selezionatrice", "talent acquisition", "ricerca e selezione"])
add(c, "impiegato-banca", "Impiegato/a di banca", "4211", ["impiegato banca", "cassiere banca", "sportellista", "operatore di sportello", "consulente bancario"])
add(c, "consulente-assicurativo", "Consulente assicurativo / subagente", "3321", ["consulente assicurativo", "agente assicurativo", "subagente", "assicurazioni", "produttore assicurativo"])
add(c, "agente-immobiliare", "Agente immobiliare", "3334", ["consulente immobiliare", "agenzia immobiliare", "mediatore immobiliare", "amministratore di condominio"])
add(c, "avvocato", "Avvocato/a", "2611", ["avvocato", "avvocata", "praticante avvocato", "legale", "studio legale"])
add(c, "traduttore", "Traduttore/traduttrice / interprete", "2643", ["traduttore", "traduttrice", "interprete", "traduzioni", "localizzazione"])

c = "informatica"
add(c, "sviluppatore-software", "Sviluppatore/sviluppatrice software", "2512", ["sviluppatore", "sviluppatrice", "programmatore", "programmatrice", "software developer", "backend", "full stack"])
add(c, "sviluppatore-web", "Sviluppatore/sviluppatrice web", "2513", ["sviluppatore web", "web developer", "frontend", "wordpress", "sviluppatore siti"])
add(c, "tecnico-informatico", "Tecnico/a informatico / helpdesk", "3512", ["tecnico informatico", "helpdesk", "supporto tecnico", "assistenza informatica", "it support"])
add(c, "sistemista", "Sistemista", "2522", ["amministratore di sistema", "system administrator", "devops", "cloud engineer"])
add(c, "tecnico-reti", "Tecnico/a di reti", "3513", ["tecnico reti", "network", "reti aziendali", "sistemista di rete"])
add(c, "analista-dati", "Analista dati", "2511", ["data analyst", "business intelligence", "data scientist", "reportistica"], V)
add(c, "cybersecurity", "Esperto/a di sicurezza informatica", "2529", ["sicurezza informatica", "security analyst", "penetration tester", "soc analyst"])
add(c, "riparazione-smartphone", "Tecnico/a riparazione PC e smartphone", "7422", ["riparazione smartphone", "riparazione pc", "tecnico telefonia", "riparazione cellulari"])
add(c, "grafico", "Grafico/a", "2166", ["grafico", "grafica", "graphic designer", "impaginatore"])
add(c, "social-media-manager", "Social media manager / addetto marketing", "2431", ["marketing", "digital marketing", "addetto marketing", "content creator", "community manager", "seo"])
add(c, "fotografo", "Fotografo/a / videomaker", "3431", ["fotografo", "fotografa", "videomaker", "operatore video", "montatore video"])
add(c, "giornalista", "Giornalista / redattore", "2642", ["redattore", "redattrice", "copywriter", "content writer"])
add(c, "tecnico-audio-luci", "Tecnico/a audio e luci", "3521", ["tecnico audio", "tecnico luci", "fonico", "service audio", "tecnico spettacolo", "montaggio palchi"])

c = "istruzione"
add(c, "insegnante-primaria", "Insegnante di scuola primaria", "2341", ["maestra", "maestro", "insegnante elementare", "docente primaria"])
add(c, "insegnante-secondaria", "Insegnante di scuola secondaria", "2330", ["professore", "professoressa", "docente scuola media", "docente superiori", "insegnante"])
add(c, "insegnante-sostegno", "Insegnante di sostegno", "2352", ["docente di sostegno", "sostegno scolastico"])
add(c, "insegnante-lingue", "Insegnante di lingue", "2353", ["insegnante inglese", "docente di lingue", "insegnante di lingua"])
add(c, "formatore", "Formatore/formatrice", "2424", ["formatore", "formatrice", "docente corsi", "trainer aziendale", "formazione professionale"])
add(c, "tutor-ripetizioni", "Tutor / insegnante di ripetizioni", "2359", ["ripetizioni", "tutor", "doposcuola", "lezioni private", "aiuto compiti"])
add(c, "istruttore-guida", "Istruttore/istruttrice di guida", "5165", ["istruttore di guida", "autoscuola", "insegnante di teoria", "istruttore patente"])
add(c, "collaboratore-scolastico", "Collaboratore/collaboratrice scolastico", "5312", ["bidello", "bidella", "personale ata"], V)
add(c, "animatore-centri-estivi", "Animatore/animatrice centri estivi e ludoteche", "5311", ["centri estivi", "grest", "ludoteca", "animatore bambini", "campus estivo"], V)

c = "tecnici"
add(c, "tecnico-meccanico", "Tecnico/a meccanico / progettista", "3115", ["tecnico meccanico", "progettista meccanico", "perito meccanico", "disegnatore meccanico"])
add(c, "disegnatore-cad", "Disegnatore/disegnatrice tecnico CAD", "3118", ["disegnatore cad", "autocad", "disegnatore tecnico", "cad operator", "solidworks"])
add(c, "tecnico-elettronico", "Tecnico/a elettronico", "3114", ["tecnico elettronico", "perito elettronico", "elettronica", "collaudatore elettronico"])
add(c, "tecnico-elettrotecnico", "Tecnico/a elettrotecnico / progettista elettrico", "3113", ["perito elettrotecnico", "progettista elettrico", "tecnico elettrico", "progettista impianti elettrici"])
add(c, "tecnico-automazione", "Tecnico/a automazione / PLC", "3114", ["plc", "automazione industriale", "programmatore plc", "tecnico automazione", "robotica"], V)
add(c, "tecnico-laboratorio-chimico", "Tecnico/a di laboratorio chimico", "3111", ["tecnico di laboratorio", "perito chimico", "analista di laboratorio", "chimico analista"])
add(c, "ingegnere-meccanico", "Ingegnere meccanico", "2144", ["ingegnere meccanico", "ingegnera meccanica"])
add(c, "ingegnere-civile", "Ingegnere civile / edile", "2142", ["ingegnere civile", "ingegnere edile", "strutturista", "progettista strutture"])
add(c, "ingegnere-elettrico", "Ingegnere elettrico / elettronico", "2151", ["ingegnere elettrico", "ingegnere elettronico", "ingegnere dell'automazione"])
add(c, "ingegnere-gestionale", "Ingegnere gestionale / di processo", "2141", ["ingegnere gestionale", "process engineer", "lean manufacturing", "ingegnere di produzione"])
add(c, "architetto", "Architetto/a", "2161", ["architetto", "architetta", "progettista edile"])
add(c, "rspp", "Tecnico/a salute e sicurezza sul lavoro (RSPP, HSE)", "2263", ["hse", "tecnico sicurezza sul lavoro", "aspp", "responsabile sicurezza"])
add(c, "tecnico-ambientale", "Tecnico/a ambientale", "2133", ["tecnico ambientale", "consulente ambientale", "rifiuti e ambiente"])
add(c, "tecnico-energetico", "Tecnico/a energetico / certificatore", "3119", ["tecnico energetico", "certificatore energetico", "ape", "energy manager"], V)

out = os.path.join(os.path.dirname(__file__), "..", "..", "data", "occupations.csv")
with open(out, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, lineterminator="\n")
    w.writerow(["slug", "label_it", "category", "isco_code", "synonyms", "note"])
    for slug, label, cat, isco, syn, note in R:
        w.writerow([slug, label, cat, isco, "|".join(syn), note])
print(f"{len(R)} mansioni scritte in data/occupations.csv")
