// API pura del modulo notifications.
export {
  ALERT_FREQUENCIES,
  ALERT_OFFERS_PER_SEARCH,
  alertFrequencyInput,
  alertIdInput,
  alertParams,
  alertQuery,
  alertsActiveFor,
  canSaveAlert,
  describeAlert,
  isAlertDue,
  JOB_ALERTS_CONSENT_VERSION,
  offerSalaryText,
  MAX_SAVED_SEARCHES,
  renderAlertEmail,
  saveAlertInput,
  UNSUBSCRIBE_TOKEN_DAYS,
  type AlertFrequency,
  type AlertOffer,
  type AlertSection,
} from "./alerts";
export {
  isNotifiedApplicationStatus,
  renderApplicationUpdate,
  renderCompanyVerified,
  renderExpiryNotice,
  renderOfferOutcome,
  renderPositionClosed,
  renderSiteOutcome,
  type ApplicationUpdate,
  type RenderedEmail,
} from "./outcomes";
export {
  MONTHLY_CHOICES,
  MONTHLY_OFFERS,
  MONTHLY_TOKEN_DAYS,
  MONTHLY_WINDOW_DAYS,
  monthlyAction,
  monthlyAnswerInput,
  monthlyChoice,
  renderMonthlyCheck,
  renderMonthlyPaused,
  type MonthlyAction,
  type MonthlyChoice,
} from "./monthly";
